### ISSUE TITLE
Slight Confusion

### ISSUE THREAD

**Issue by daleharvey** [zemirco/couchdb-cookie-auth#1]
Hey, thanks for the post, this is awesome and very much in line with things I want to get documented soon

So for my confusion on twitter, I did a similiar setup with http://done.gd and https://github.com/daleharvey/couch-persona

In this case my app / auth server is on http://persona.pouchdb.com and my couch is on http://couchdb.pouchdb.com/

The first time I did it I also wanted to do a no proxy, talk directly to couchdb type setup, I did my auth via persona.pouchdb.com, it returned the AuthSession from couchdb as json, I then set my cookie manually on the client and it mostly worked, chrome did not love me manually setting a cookie (https://github.com/daleharvey/pouchdb/blob/master/lib/deps/ajax.js#L152) and I think I hit up against other issues so I switched to just doing as you do, responding from the server with a set-cookie, but that cookie is only going to be set for the domain you run app.js from, not for localhost:5984, so I proxy db requests https://github.com/daleharvey/couch-persona/blob/master/couch-persona.js#L188

**Comment by zemirco** [comment]
I've got my app running on [localhost:3000](http://localhost:3000/) and my CouchDB on [localhost:5984](http://localhost:5984/).

Now I'm confused, too. It shouldn't work because the cookie from `3000` isn't sent to `5984`, right? But somehow it does. When I remove 

``` js
res.cookie('AuthSession', cookies.AuthSession);
```

and refresh the page I get the basic auth popup asking for password and username. I don't know the PouchDB code in depth but found 

```
xhr.withCredentials = true;
```

at [ajax.js#L132](https://github.com/daleharvey/pouchdb/blob/master/lib/deps/ajax.js#L132). With the `withCredentials` flag set to `true` we are able to send cookies across domains.

**Comment by daleharvey** [comment]
without `withCredentials` no cookies will get sent at all, however they should still follow the same origin policy and only send cookies pertaining to that domain (+host)

Gonna take a look into this when I have time

**Comment by zemirco** [comment]
Closing the issue for now.
