### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by jprichardson** [zemirco/couchdb-cookie-auth#2]
Very timely! Thanks for posting this. Is this method possible to use without a proxy? i.e. I'd like to use Cloudant, but I want my clientside Pouchdb app to be able to create a new database directly on Cloudant and directly interact with it. I'd also like my client app to be able to provide some recovery key of some sort and to be able to sync with the server should the client app get deleted. (This is all in Phonegap btw). But it seems that I'll need to setup a proxy to create a new user / pw combo and proxy on the `AuthSession` key. 

Thoughts?

**Comment by zemirco** [comment]
Yes, you can do the whole user authentication directly from the browser without any proxy in between. Make sure you set `require_valid_user = false`. With this flag everybody is allowed to make requests to your db. 

That's why you have to check for valid users on every requests. Do this by creating a design document that has a `validate_doc_update` function.

``` js
{
  "_id": "_design/anything",
  "validate_doc_update":
  "function(newDoc, oldDoc, userCtx, secObj) {
    if(!userCtx.name) {
      throw({forbidden: 'Please login.'})
    }
  }"
}
```

I've written a small [sample app](https://github.com/zeMirco/couchdb-browser-auth) where you create, login, make requests and logout from the browser.

**Comment by gockxml** [comment]
Thank you so much! The two sample projects are really helpful for beginners like me since there are little docs and examples about couchdb/pouchdb. Awesome!

**Comment by zemirco** [comment]
Thank you!
